### ISSUE TITLE
Adding tests

### ISSUE THREAD

**Issue by jaurentz** [eiscor/eiscor#13]
We need more tests! I still believe every subroutine should also have a corresponding test. We need to think about a standard format for tests and then get to it.

**Comment by thomasmach** [comment]
Besides the runtime we are also interested in the accuracy. I suggest that we allow the test_functions to have two numbers as output, the time and an accuracy benchmark.
This would allow us to optimize the underlying computational functions for both relevant criteria. I mainly think about __turnover__, __vec3gen__, or __fuse__. Other functions like __scalar_infcheck__ are either correct or wrong and don't have an accuracy.

**Comment by jaurentz** [comment]
I'm not sure if there really is a good reason for tests to output time. It's not as if we are outputting the average time of a turnover. As for accuracy that seems tricky. How do we measure accuracy? As an average or compare prescribed examples against some benchmark? I guess overall the tests should be binary, either the subroutine works or it doesn't. Your DEBUG mode blocks make it easy to output more states when necessary/desired.

**Comment by jaurentz** [comment]
Maybe we should define another preprocessor flag for verbose output in tests? 

-DVERBOSE or -DPRINT

**Comment by thomasmach** [comment]
I think we need another flag. I prefer -DVERBOSE.

**Comment by jaurentz** [comment]
This can be added to the eiscor.h file following the same template as the DEBUG flag.

**Comment by jaurentz** [comment]
We seem to be happy with the current state of tests so I'm closing this.
