### ISSUE TITLE
INFO code guidelines

### ISSUE THREAD

**Issue by jaurentz** [eiscor/eiscor#34]
We should set INFO code guidelines somewhere.

**Comment by thomasmach** [comment]
See https://github.com/eiscor/eiscor/wiki/INFO-code-guidelines.
When the guidelines are set, we should check/adopt the subroutines.

**Comment by jaurentz** [comment]
This points to #9

**Comment by jaurentz** [comment]
This points to #2

**Comment by jaurentz** [comment]
I've been looking at more and more of these info code blocks and I am not happy with them. There are two things that really bother me:
+ they are too complicated
+ they are a pain to modify when an interface is changed

We need a simpler but nearly as effective way to pass error information. My first thought is to only let a hand full of subroutines return INFO codes different than 0 or 1. I'm thinking the subroutines that are designed specifically for validation. When one of these routines catches an error it will print a useful error message and all other routines will simply point to the point of error through a trace back.

**Comment by thomasmach** [comment]
I spend a whole day last Friday, modifying these blocks. Hence I totally agree with your observations.

In the expert routines the validation is not in a DEBUG block and there it is actually really necessary. The info codes only used during debugging are not so important. If something goes wrong, we can either start with valgrind providing us line numbers, or we start bringing the debug info block up-to-date.

**Comment by jaurentz** [comment]
Even in DEBUG mode all we need is a trace back to where the error happened. Once we're pointed to the right spot we can deduce the error ourselves. The trace back is simply a file name and a line number which we mostly have already. I will think about this some more.

**Comment by jaurentz** [comment]
I think we have since stripped out many info codes so this can be closed.
