### ISSUE TITLE
Renormalizing unitary factors

### ISSUE THREAD

**Issue by jaurentz** [eiscor/eiscor#43]
Issue #27 addressed the issue of complex abs which shows up often in renormalizations. In most cases it is possible to use d_rot2_vec2gen or z_rot3_vec3gen to renormalize. Should this become standard practice? If so there are still subroutines that do not follow this convention.

**Comment by thomasmach** [comment]
Yes, that should become standard procedure.

**Comment by jaurentz** [comment]
A quick grep in development shows that the compiler abs is used almost exclusively in if statements. This seems fine to me so I'm closing.
