### ISSUE TITLE
Is the interface block for the FUN argument in twisted QZ necessary?

### ISSUE THREAD

**Issue by jaurentz** [eiscor/eiscor#45]
In z_upr1fact_twistedqz we define an interface for the FUN argument so that we know exactly what arguments the function FUN takes as input. Whenever I call a function in BLAS all I ever do is declare the return type without using an interface block. Should we do the same in this instance as well?

**Comment by thomasmach** [comment]
Indeed, I also just define the output for BLAS functions. However, I think it's more safe with the interface block, since the additional information might be used by the compiler.

**Comment by jaurentz** [comment]
We were worried earlier about specify a FUN that uses past shift information or something beyond the current ordering. Maybe if we don't specify an interface we don't have to worry about what kind of arguments FUN takes.

On the other hand, it is difficult to check for errors if the interface isn't specified.

**Comment by thomasmach** [comment]
The function is called anyway, and at latest then the type of the arguments have to been known.

**Comment by jaurentz** [comment]
Since we don't yet have a practical application for the fun input I'm closing this issue.
