### ISSUE TITLE
Adding rotation validating subroutines

### ISSUE THREAD

**Issue by jaurentz** [eiscor/eiscor#47]
For input checking we often find ourselves checking the validity of rotations and sequences of rotations, as well as the validity of diagonal D's (same as rot2 validation).  Should we create special routines for this ?

d_rot2_check
z_rot3_check

We could then extended this to sequences of rotations.

d_rot2seq_check
z_rot3seq_check

This would unify all our factor check routines.

**Comment by thomasmach** [comment]
Sounds good.

**Comment by jaurentz** [comment]
I've created a new branch __feature_rotation_checks__ that implements the first two routines. If they seem satisfactory I will move ahead the other and create some tests.

**Comment by thomasmach** [comment]
The two routines look good.

**Comment by jaurentz** [comment]
This is now being handled in the branch __set-core-subroutines__
