### ISSUE TITLE
AMVW is two times faster than EISCOR

### ISSUE THREAD

**Issue by thomasmach** [eiscor/eiscor#49]
I compared the simple case of computing the roots of unity via the polynomial z^n - 1 = 0.

| N | eiscor | AMVW |
| --- | --- | --- |
| 512 | 0.10 s | 0.05s |
| 1024 | 0.36 s | 0.19 s |
| 2048 | 1.375 s | 0.79 s |

The test is based on branch feature-twisted-upr1.

Possible optimization: 
- **z_upr1fact_rot3throughtri** does not track the if the rotations B_i = C_i^H, and thus always compute two turnovers, while AMVW keeps track and uses only one turnover.

**Comment by jaurentz** [comment]
In general the upper-triangular parts may not be I plus rank one. Do we need a special flag for this?

**Comment by thomasmach** [comment]
Do you mean they can have a lower or higher rank?

**Comment by jaurentz** [comment]
My mistake. Yes we should add such a feature. I will think about this.

**Comment by thomasmach** [comment]
Another possible optimization:
+ __z_rot3_turnover__ or __z_rot3_vec3gen__: In AMVW's turnover the normalization is only down if necessary, by checking the nrm first.

**Comment by jaurentz** [comment]
Can this be done in a robust way?

**Comment by thomasmach** [comment]
We did it in AMVW and I thought it was robust there.

**Comment by thomasmach** [comment]
Doing the normalization in the turnover only if  (|cr^2 + ci^2 + s^2 -1| > tol) has the following effect:

N | eiscor | eiscor turnover with check | AMVW
------------ | -------------  | -------------  | ------------- 
512 | 0.10 s | 0.066 s | 0.04s
1024 | 0.36 s | 0.25 s | 0.16 s
2048 | 1.375 s | 0.99 s | 0.63 s
4096 | 5.453 s | 3.979 s | 2.462 s

**Comment by thomasmach** [comment]
I found another difference to AMVW: __z_upr1fact_singlestep__ the Wilkinson shift is not compute correctly. By replacing the shift computation in the QR case, I could reduce the iteration count for N=4096 from 9289 to 8223 (exactly the same as for AMVW) and the runtime from 3.97 s to 3.46 s. (eiscor (1.13e-11) is in this example 4 times more accurate than AMVW (6.18e-11))

**Comment by jaurentz** [comment]
The turnover check is pretty amazing. We will have to look into this some more. My guess is that this is more likely to decrease runtimes than assembly code. We just have to figure out how to do it in a robust way.

**Comment by jaurentz** [comment]
This renormalization check can actually be done inside of the rot*_vec*gen routines and could speed up everything in the new core subroutines branch.

**Comment by thomasmach** [comment]
I replaced:

    call z_rot3_vec3gen(T(1),T(2),T(3),c4r,c4i,s4,nrm,INFO)

with

    nrm = T(1)*T(1) + T(2)*T(2) + T(3)*T(3)
    if (dabs(nrm-1d0)<tol) then
      c4r = T(1)
      c4i = T(2)
      s4  = T(3)
      nrm = 1d0
    else
      call z_rot3_vec3gen(T(1),T(2),T(3),c4r,c4i,s4,nrm,INFO)
    end if

and I think that's robust. And you are right, it should be done in rot_vecgen.

**Comment by thomasmach** [comment]
In eiscor we decided to use d/z_rot2/3_vec2/3gen for normalization. This is the cause of a substantial part (~0.6s) of the remaining speed difference between AMVW and eiscor. However, eiscor is also half a digit more accurate for N = 4096 in the above mentioned example.

I also tried to figure out how much time we loose by the overhead for the twisted shape, its 0.2s, I think.

**Comment by jaurentz** [comment]
The nice thing about the normalization scheme is that speeding up 2 subroutines speeds up everything. I still believe it is the correct thing to do.

**Comment by thomasmach** [comment]
I agree. We should keep the normalization as it is now. We have a more accurate solution and with some small changes in the normalization routines we can trade accuracy for speed.

**Comment by jaurentz** [comment]
PR #77 likely fixes a lot of this. I still have other ideas based on some observations in the unitary code but this will take some time. Closing this until I have time to make the changes.
