### ISSUE TITLE
The core of EISCOR

### ISSUE THREAD

**Issue by jaurentz** [eiscor/eiscor#50]
I think we should somehow distinguish the core subroutines in eiscor from the more general ones. Something like BES (Basic Eiscor Subroutines). These routines are special in that nearly every other routine relies on them so modifications to these cascade through the rest of the software.

It should be very difficult to make changes to these for reasons of stability and we should not modify them without thorough testing and discussion.

**Comment by thomasmach** [comment]
It's only 5 routines:
+ z_rot3_vec3gen
+ z_rot3_vec4gen
+ z_rot3_turnover
+ d_rot2_vec2gen
+ d_rot2_turnover

Do you want to move them to a separate directory?

**Comment by jaurentz** [comment]
I'm not sure how to distinguish them. We may also add z_2x2array_eig and geneig but I'm not sure. I just feel that these should some how be protected.

**Comment by jaurentz** [comment]
I think classifying the subroutines will help us guide us on what each type of routine needs. Some possible classifications could be:
+ core computation
+ expert/user level
+ core validation
+ orthfact/unifact only
+ upr1fact only

Each classification could have a basic contract which programmers must adhere to. Every subroutine can only belong to a single class.

**Comment by thomasmach** [comment]
I think there are different options:
+ The most radical one: We put them in a separate git repository. Maybe together with possible optimized assembly code.
+ We put them in a separate directory.
+ We mark them with a X in the file name.
+ We don't mark them at all and just add a guideline, what changes in these functions should always be emphasized in a pull request and checked especially.

The core subroutines need special tests (timings?), too.

**Comment by jaurentz** [comment]
I'm not sure about the separate repo, though it has crossed my mind.

**Comment by jaurentz** [comment]
This is being handled with branch __set-core-subroutines__
