### ISSUE TITLE
Using OpenBLAS

### ISSUE THREAD

**Issue by jaurentz** [eiscor/eiscor#51]
I created a branch called **use-openblas** that calls **drotg.f** from the OpenBLAS ubuntu package inside of d_rot2_vec2gen.f90. According to the benchmark routine, OpenBLAS is slightly more accurate (about 2 times on my machine) and 4 times as slow! This is not so surprising as OpenBLAS does best in the level 3 routines. This is not an argument against assembly code but it does give some evidence that customizing assembly code may give little to no improvement.

It also isn't entirely clear to me how well the Ubuntu package is built.

**Comment by thomasmach** [comment]
On my machine OpenBLAS is 2 times slower and 2 times more accurate.

**Comment by jaurentz** [comment]
This is never going to happen, so closing.
