### ISSUE TITLE
When and where to use an INFO parameter?

### ISSUE THREAD

**Issue by jaurentz** [eiscor/eiscor#52]
I've started pulling in upr1fact routines from **development** to **set-core-subroutines** and am running into INFO code questions. I think we've established that core routines will no longer use an INFO code, but we have yet to establish when to use INFO codes in more specialized routines. I've begun to modify https://github.com/eiscor/eiscor/blob/set-core-subroutines/src/complex_double/z_upr1fact_deflationcheck.f90 and am not sure if I should remove the INFO parameter or not. I would like to remove it but only if we can avoid segfaults.

**Comment by thomasmach** [comment]
The routine z_upr1fact_deflationcheck.f90 only tests the input. I agree that it makes sense to remove the INFO parameter. I guess with sufficient testing we can be sure that none of the internal routines are called with an invalid input (except maybe NANs and INFs). That's different for the expert routines, but there we are testing the input anyway.

**Comment by jaurentz** [comment]
I'm thinking of ways to make the input for this routine less likely to cause errors. My ultimate goal is to remove the INFO parameter for all but the expert routines. Hopefully in a robust way.

**Comment by thomasmach** [comment]
I replaced:

    call z_rot3_vec3gen(T(1),T(2),T(3),c4r,c4i,s4,nrm,INFO)

with

    nrm = T(1)*T(1) + T(2)*T(2) + T(3)*T(3)
    if (dabs(nrm-1d0)<tol) then
      c4r = T(1)
      c4i = T(2)
      s4  = T(3)
      nrm = 1d0
    else
      call z_rot3_vec3gen(T(1),T(2),T(3),c4r,c4i,s4,nrm,INFO)
    end if

and I think that's robust.

**Comment by jaurentz** [comment]
I think we're happy enough with the current situation that I can close this.
