### ISSUE TITLE
Bug in upr1 twisted qz

### ISSUE THREAD

**Issue by thomasmach** [eiscor/eiscor#53]
I run the test (test_z_upr1fact_twistedqz_bug), which I added with commit 86223bf to the branch feature-upr1-twistedqz. 

The tests runs the Hessenberg QR for the roots of unity example and then computes the argument of the eigenvalues. The argument should be j 2 pi, with j=0,...,N. Each j should only occur once. For some random seeds, however, the same j occurs multiple times indicating that the same eigenvalue is found twice, while others are missing.

Note: Each computed eigenvalue is close to an actual eigenvalue. 
Note 2: This bug does not occur in AMVW.

**Comment by jaurentz** [comment]
This should be fixed with new PR.
