### ISSUE TITLE
accuracy of eigenvectors in z_2x2array_eig

### ISSUE THREAD

**Issue by jaurentz** [eiscor/eiscor#66]
The schurvectors in `z_2x2array_eig` may be computed inaccurately due to cancellation. This appears to be an implementation error.

**Comment by thomasmach** [comment]
Did pull request #68 fixed this issue?

**Comment by jaurentz** [comment]
I can't say for sure. I certainly haven't investigated the generalized case and I would prefer to leave this issue open as a reminder.

**Comment by jaurentz** [comment]
We have switched all bulge-chasing routines to now solve the 2x2 problems by bulge-chasing. Therefore this is irrelevant.
